package ddcongen;
public class ActionTemplate {
	static String template = "module.exports = {\r\n"
			+ "\r\n"
			+ "    name: \"${DDConGen_MOCKNAME}\",\r\n"
			+ "\r\n"
			+ "    title: \"${DDConGen_MOCKNAME}\",\r\n"
			+ "\r\n"
			+ "    version: \"${DDConGen_MOCKVERSION}\",\r\n"
			+ "\r\n"
			+ "    description: ``,\r\n"
			+ "    \r\n"
			+ "    mock_input: \r\n"
			+ "		${DDConGen_MOCKINPUT},\r\n"
			+ "	\r\n"
			+ "\r\n"
			+ "    input: \r\n"
			+ "        ${DDConGen_INPUTSCHEMA}\r\n"
			+ "            \r\n"
			+ "\r\n"
			+ "    output: {\r\n"
			+ "        title: \"output\",\r\n"
			+ "        type: \"object\",\r\n"
			+ "            properties: {\r\n"
			+ "                \"title\": \"Output\",\r\n"
			+ "                \"type\": \"object\",\r\n"
			+ "                \"properties\": {\r\n"
			+ "                        \r\n"
			+ "            }\r\n"
			+ "        }\r\n"
			+ "    },\r\n"
			+ "\r\n"
			+ "    execute: function(input, output) {\r\n"
			+ "        var global_constants = require(\"../../common/constants\");\r\n"
			+ "        var api_domain = \"${DDConGen_APIDOMAIN}\";\r\n"
			+ "        var request = require(\"request\");\r\n"
			+ "        var option = {\r\n"
			+ "            \"method\": \"${DDConGen_METHOD}\",\r\n"
			+ "            \"headers\": global_constants.generate_common_header(input),\r\n"
			+ "            ${DDConGen_BODY}"
			+ "            \"url\": global_constants.get_uri(input.auth.site,api_domain)+\\`${DDConGen_APIPATH}\\`,\r\n"
			+ "			\"qs\":{ ${DDConGen_APIQS} }\r\n"
			+ "        }\r\n"
			+ "        request(option, function(error, response, body) {\r\n"
			+ "            if (error) {\r\n"
			+ "                output(error);\r\n"
			+ "            }\r\n"
			+ "            if (response.statusCode === ${DDConGen_SUCCESSCODE}) {\r\n"
			+ "                output(null, body);\r\n"
			+ "            }\r\n"
			+ "            else {\r\n"
			+ "                if(body) {\r\n"
			+ "                    output(body,null)\r\n"
			+ "                }\r\n"
			+ "                else {\r\n"
			+ "                    output(`{\"status\": false,\"statusMessage\": ${response.statusMessage}}`,null)\r\n"
			+ "                }\r\n"
			+ "            }\r\n"
			+ "        });\r\n"
			+ "    }\r\n"
			+ "}";
	
}